routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*Route::group(["middleware" => "auth", "namespace" => "Admin"], function(){
	Route::get('/dashboard', 'DashboardController@adminDashboard')->name('admindashboard');
	Route::get('/userdashboard', 'DashboardController@userDashboard')->name('userdashboard');
});*/

Route::namespace('Admin\Login')->group(function(){
	Route::get('/login', 'LoginController@showForm')->name('login');
	Route::post('/login', 'LoginController@login');
	Route::post('/logout', 'LoginController@logout')->name('logout');
});

Route::group(["middleware" => ["auth","preventBackHistory"], "namespace" => "Admin"], function(){
	Route::get('/dashboard', 'DashboardController@adminDashboard')->name('admindashboard');
	Route::get('/userdashboard', 'DashboardController@userDashboard')->name('userdashboard');
});

Route::namespace('Admin\Auth')->group(function(){
	Route::get('/login', 'LoginController@showForm')->name('login');
	Route::post('/login', 'LoginController@login');
	Route::post('/logout', 'LoginController@logout')->name('logout');
	Route::get('/passwordReset', 'ForgetPasswordController@showForm')->name('password.request');
	Route::post('/password/email', 'ForgetPasswordController@sendEmail')->name('password.email');
	Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
	Route::post('password/reset', 'ResetPasswordController@resetPassword')->name('password.update');
});

Route::namespace('Admin\User')->group(function(){
	Route::prefix('users')->name('users.')->group(function(){
		Route::get('/', 'UsersController@index')->name('index');
		Route::get('/register', 'UsersController@create')->name('create');
		Route::post('/', 'UsersController@store')->name('store');
		Route::get('/edit/{id}', 'UsersController@edit')->name('edit');
		Route::put('/{id}', 'UsersController@update')->name('update');
		Route::delete('/delete/{id}', 'UsersController@destroy')->name('delete');
		Route::post('/{id}', 'UsersController@status')->name('status');
	});
});

Route::namespace('Admin\Exhibition')->group(function(){
	Route::prefix('exhibitions')->name('exhibitions.')->group(function(){
		Route::get('/', 'ExhibitionController@index')->name('index');
		Route::get('/create', 'ExhibitionController@create')->name('create');
		Route::post('/', 'ExhibitionController@store')->name('store');
		Route::get('view/{id}', 'ExhibitionController@show')->name('show');
		Route::get('/edit/{id}', 'ExhibitionController@edit')->name('edit');
		Route::put('/{id}', 'ExhibitionController@update')->name('update');
		Route::delete('/delete/{id}', 'ExhibitionController@destroy')->name('delete');
		Route::post('/{id}', 'ExhibitionController@status')->name('status');
	});
});

Route::namespace('Admin\Painting')->group(function(){
	Route::prefix('paintings')->name('paintings.')->group(function(){
		Route::get('/', 'PaintingController@index')->name('index');
		Route::get('/create', 'PaintingController@create')->name('create');
		Route::post('/', 'PaintingController@store')->name('store');
		Route::get('/edit/{id}', 'PaintingController@edit')->name('edit');
		Route::put('/{id}', 'PaintingController@update')->name('update');
		Route::delete('/delete/{id}', 'PaintingController@destroy')->name('delete');
		Route::post('/{id}', 'PaintingController@status')->name('status');
		Route::get('listing', 'PaintingController@listing')->name('listing');
		Route::get('detail/{id}', 'PaintingController@show')->name('detail');
	});
});

Route::namespace('Admin')->group(function (){
	Route::get('export', 'ExportController@export')->name('export');
});

/*Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');*/

app/Painting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;
use App\Exhibition;

class Painting extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'exhibition_id', 'name', 'image', 'status',
    ];

    /**
     * Scope a query to search users.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
    */
    public function scopeFilter($query, $value)
    {
        $query->where('name', 'LIKE', "%$value%");
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function exhibition()
    {
        return $this->belongsTo('App\Exhibition');
    }
}

app/Http/Controllers/API/PaintingController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Repositories\PaintingRepository;
use League\Fractal\Resource\Collection;
use League\Fractal\Resource\Item;
use League\Fractal\Manager;
use League\Fractal\Serializer\JsonApiSerializer;
use League\Fractal\Pagination\IlluminatePaginatorAdapter;
use App\Transformers\paintingTransformer;
use Validator;

class PaintingController extends Controller
{
    protected $painting;

    public function __construct(PaintingRepository $painting)
    {
        $this->painting = $painting;
    }

    /**
     * Get ALl Painting List
     * @return \IIluminate\Http\Response
     */
    public function index(Request $request)
    {
    	$paginator = $this->painting->getPaginate($request);
    	$paintings = $paginator->getCollection();
    	$manager = new Manager();
        $manager->setSerializer(new JsonApiSerializer(url('api')));
    	$resource = new Collection($paintings, new paintingTransformer());
    	$result = $resource->setPaginator(new IlluminatePaginatorAdapter($paginator));
    	return response()->json($manager->createData($result)->toArray());
    }

    /**
     * Store a newly created Painting in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		$validator = Validator::make($request->all(), [ 
	        'exhibition' => 'required',
	        'name' => 'required',
	        'image' => 'mimes:jpeg,jpg,png,gif|required',
            'status' => 'accepted',
	    ]);
	    if ($validator->fails()) { 
	        return response()->json(['error'=>$validator->errors()], 401);            
	    }
    	$user = $request->user();
    	$request['user_id'] = $user->id;
		$this->painting->store($request);
        $painting = $this->painting->latestRecord();
        $manager = new Manager();
        $manager->setSerializer(new JsonApiSerializer(url('api')));
        $resource = new Item($painting, new paintingTransformer(), 'Painting');
        $result = $manager->createData($resource)->toArray();
        return $result;
    }

    /**
     * Show Specific Painting
     * @return \IIluminate\Http\Response
     */
    public function show($id)
    {
		$painting = $this->painting->find($id);
    	$manager = new Manager();
    	$manager->setSerializer(new JsonApiSerializer(url('api')));
    	$resource = new Item($painting, new paintingTransformer(), 'Painting');
    	$result = $manager->createData($resource);
    	return $result->toArray();
    }

    /**
     * @param [int] $id
     * @param \IILuminate\Http\Request $request
     * @return \IILuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    	
    	$this->painting->update($id, $request);
		$painting = $this->painting->find($id);
    	$manager = new Manager();
    	$manager->setSerializer(new JsonApiSerializer(url('api')));
    	$resource = new Item($painting, new paintingTransformer(), 'Painting');
    	$result = $manager->createData($resource)->toArray();
    	return $result;
    }

    /**
     * @param [int] $id
     * @return \IIluminate\Http\Response
     */
    public function destroy($id)
    {
    	$this->painting->delete($id);
    	return response()->json(['message' => 'Painting Deleted Successfully']);
    }
}

app/Http/Controllers/Admin/Painting/PaintingController.php
<?php

namespace App\Http\Controllers\Admin\Painting;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Repositories\PaintingRepository;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\PaintingStoreRequest;
use App\Exhibition;

class PaintingController extends Controller
{
    protected $paintings;

    public function __construct(PaintingRepository $painting)
    {
        $this->paintings = $painting;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {   
        $request['user_id'] = Auth::id();
        $paintings = $this->paintings->paginate($request);
        return view('admin.paintings.painting', [
            'paintings' => $paintings
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function listing(Request $request)
    {   
        $paintings = $this->paintings->getPaginate($request);
        return view('admin.paintings.paintingListing', [
            'paintings' => $paintings
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $exhibitions = $this->paintings->getExhibition();
        return view('admin.paintings.create', [
            'exhibitions' => $exhibitions
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PaintingStoreRequest $request)
    {
        $request['user_id'] = Auth::id();
        $this->paintings->store($request);
        return redirect()->route('paintings.index')->with('message', 'Painting Added Successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $painting = $this->paintings->find($id);
        $exhibitions = $this->paintings->getExhibition();
        return view('admin.paintings.edit')->with(['painting' => $painting, 'exhibitions' => $exhibitions]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PaintingStoreRequest $request, $id)
    {
        $this->paintings->update($id, $request);
        return redirect()->route('paintings.index')->with('message', 'Painting Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->paintings->delete($id);
        return redirect()->route('paintings.index')->with('message', 'Painting Deleted Successfully');
    }

    /**
     * Update the specified Painting Status in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function status(Request $request, $id)
    {
        $this->paintings->statusUpdate($id, $request);
        return redirect()->route('paintings.index')->with('message', 'User Status Updated Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $paintings = $this->paintings->detail($id);
        return view('admin.paintings.detail')->with(['paintings' => $paintings]);
    }
}

resources/views/admin/paintings/create.blade.php
@extends('admin.layout.userMaster')
@section('title', 'Dashboard')
@section('content')
	<!-- Breadcrumbs-->
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="#">Artist Dashboard</a>
		</li>
		<li class="breadcrumb-item active">Overview</li>
	</ol>

	<!--Form Area-->
	<div class="row">
		<div class="col-xl-12 col-sm-12 mb-12">
			<div class="card o-hidden h-100">
				<div class="card-header d-flex justify-content-between align-items-center">
					<h4>
						Add Painting
					</h4>
					<a href="{{ route('paintings.index') }}" class="btn btn-success">
						Back
					</a>
				</div>
				<div class="card-body">
					<form action="{{ route('paintings.store') }}" method="POST" enctype="multipart/form-data">
						@csrf
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>Exhibitions:</label>
									<select name="exhibition" class="form-control">
										<option value="">Select Exhibition</option>
										@foreach($exhibitions as $exhibition)
											<option value="{{$exhibition->id}}">{{$exhibition->name}}</option>
										@endforeach
									</select>
									@error('exhibition')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>Name:</label>
									<input type="text" name="name" class="form-control" value="{{ old('name') }}">
									@error('name')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>Image:</label>
									<input type="file" name="image" class="form-control">
									@error('image')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>Status:</label>
									<input type="hidden" name="status" value="0">
									<input type="checkbox" name="status" value="1" class="mt-1" @if(old('status')=='1')) checked @endif>
									@error('status')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<input type="submit" name="Painting" value="Add" class="btn btn-primary">
								</div>
							</div>
						</div>
					</form>	
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/admin/paintings/detail.blade.php
@extends('admin.layout.master')
@section('title', 'Dashboard')
@section('content')
	<!-- Breadcrumbs-->
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="#">Admin Dashboard</a>
		</li>
		<li class="breadcrumb-item active">Overview</li>
	</ol>

	<!-- Exhibitions Listing-->
	<div class="row">
		<div class="col-xl-12 col-sm-12 mb-12">
			@if(session()->has('message'))
			    <div class="alert alert-success">
			        {{ session()->get('message') }}
			    </div>
			@endif
			<div class="card o-hidden h-100">
				<div class="card-header d-flex justify-content-between align-items-center">
					<h4>
						Painting Detail
					</h4>
					<a href="{{ route('paintings.listing') }}" class="btn btn-success">
						Back
					</a>
				</div>
				<div class="card-body">	
					<div class="table-responsive">
						<table class="table table-bordered">
						    <tbody>
								<tr>
									<th>User Name:</th>
									<td>{{$paintings->user->name}}</td>
								</tr>
								<tr>
									<th>User Email:</th>
									<td>{{$paintings->user->email}}</td>
								</tr>
								<tr>
									<th>Exhibition Name:</th>
									<td>{{$paintings->exhibition->name}}</td>
								</tr>
								<tr>
									<th>Exhibition Start Date:</th>
									<td>{{date('d/m/Y', strtotime($paintings->exhibition->start_datetime))}}</td>
								</tr>
								<tr>
									<th>Exhibition End Date:</th>
									<td>{{date('d/m/Y', strtotime($paintings->exhibition->end_datetime))}}</td>
								</tr>
								<tr>
									<th>Exhibition Address:</th>
									<td>{!!$paintings->exhibition->address!!}</td>
								</tr>
								<tr>
									<th>Exhibition City:</th>
									<td>{{$paintings->exhibition->city}}</td>
								</tr>
								<tr>
									<th>Exhibition State:</th>
									<td>{{$paintings->exhibition->state}}</td>
								</tr>
								<tr>
									<th>Painting Name:</th>
									<td>{{$paintings->name}}</td>
								</tr>
								<tr>
									<th>Painting Image:</th>
									<td>
										<img src="{{ asset('images/'.$paintings->image) }}" alt="...">
									</td>
								</tr>
						    </tbody>
						  </table>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/admin/paintings/edit.blade.php
@extends('admin.layout.userMaster')
@section('title', 'Dashboard')
@section('content')
	<!-- Breadcrumbs-->
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="#">Artist Dashboard</a>
		</li>
		<li class="breadcrumb-item active">Overview</li>
	</ol>

	<!--Form Area-->
	<div class="row">
		<div class="col-xl-12 col-sm-12 mb-12">
			<div class="card o-hidden h-100">
				<div class="card-header d-flex justify-content-between align-items-center">
					<h4>
						Edit Painting
					</h4>
				</div>
				<div class="card-body">
					<form action="{{ route('paintings.update', ['id' => $painting->id]) }}" method="POST" enctype="multipart/form-data">
						@method('PUT')
						@csrf
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>Exhibitions:</label>
									<select name="exhibition" class="form-control">
										<option value="">Select Exhibition</option>
										@foreach($exhibitions as $exhibition)
											<option value="{{$exhibition->id}}"
												@if($exhibition->id == $painting->exhibition_id)
													{{'Selected'}}
												@endif
											>
												{{$exhibition->name}}
											</option>
										@endforeach
									</select>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>Name:</label>
									<input type="text" name="name" class="form-control" value="{{ $painting->name }}">
									@error('name')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>Image:</label>
									<input type="file" name="image" class="form-control">
									<img src="{{ asset('images/'.$painting->image) }}" alt="..." height="50px" width="50px">
									@error('image')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<label>Status:</label>
								<input type="hidden" name="status" value="0">
								<input type="checkbox" name="status" value="1" @if($painting->status==1){{'checked'}}@endif>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<input type="submit" name="Painting" value="Update" class="btn btn-primary">
									<a href="{{ route('paintings.index') }}" class="btn btn-success">
										Back
									</a>
								</div>
							</div>
						</div>
					</form>	
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/admin/paintings/painting.blade.php
@extends('admin.layout.userMaster')
@section('title', 'Dashboard')
@section('content')
	<!-- Breadcrumbs-->
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="#">Artist Dashboard</a>
		</li>
		<li class="breadcrumb-item active">Overview</li>
	</ol>

	<!-- Painting Listing-->
	<div class="row">
		<div class="col-xl-12 col-sm-12 mb-12">
			@if(session()->has('message'))
			    <div class="alert alert-success">
			        {{ session()->get('message') }}
			    </div>
			@endif

			<div class="card o-hidden h-100">
				<div class="card-header d-flex justify-content-between align-items-center">
					<h4>
						Painting Listing
					</h4>
					<form action="{{ route('paintings.index') }}" method="GET" role="search" class="d-flex">
						<input type="text" class="form-control" placeholder="Search" name="name" value="{{ Request::input('name') }}" required>
						<div class="input-group">
							&nbsp;
							<input type="submit" value="Search" class="btn btn-info">
							&nbsp;
							<a href="{{ route('paintings.index') }}" class="btn btn-success">Reset</a>
						</div>
					</form>
					<a href="{{ route('paintings.create') }}" class="btn btn-success">
						Add Painting
					</a>
				</div>
				<div class="card-body">
					<div class="table-responsive">          
						<table class="table table-bordered">
							<thead>
								<tr>
									<th>Id</th>
									<th>Name</th>
									<th>Image</th>
									<th>Status</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								@if(count($paintings) > 0)
									@foreach($paintings as $painting)
										<tr>
											<td>{{$painting->id}}</td>
											<td>{{$painting->name}}</td>
											<td>
												<img src="{{ asset('images/'.$painting->image)}}" alt="..." style="height: 50px; width: 50px;">
											</td>
											<td>
												<form action="{{ route('paintings.status', ['id' => $painting->id]) }}" method="POST">
													{{ csrf_field() }}
													@if($painting->status == 1)
														<input type="hidden" name="status" value="0">
														<button type="submit" class="btn btn-success">
															<i class="fas fa-user-check" style="font-size: 10px;"></i>
														</button>
													@else
														<input type="hidden" name="status" value="1">
														<button type="submit" class="btn btn-danger">
															<i class="fas fa-window-close" style="font-size: 10px;"></i>
														</button>
													@endif
												</form>
											</td>
											<td class="d-flex">
												<form method="POST" action="{{ route('paintings.delete', ['id' => $painting->id]) }}">
												    {{ csrf_field() }}
												    {{ method_field('DELETE') }}
												    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">
												    	<i class="fas fa-trash-alt"></i>
												    </button>
												</form>
												<a href="{{ route('paintings.edit', ['id' => $painting->id]) }}" class="btn btn-info ml-1" style="height: 30px; width: 42px;">
													<i class="far fa-edit"></i>
												</a>
											</td>
										</tr>
									@endforeach
								@else
									<tr>
										<td colspan="5">{{ 'No Record Found ! Try Again!!' }}</td>
									</tr>
								@endif
							</tbody>
						</table>
						{{ $paintings->links() }}
					</div>	
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/admin/paintings/paintingListing.blade.php
@extends('admin.layout.master')
@section('title', 'Dashboard')
@section('content')
	<!-- Breadcrumbs-->
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="#">Admin Dashboard</a>
		</li>
		<li class="breadcrumb-item active">Overview</li>
	</ol>
	<!-- Painting Listing-->
	<div class="row">
		<div class="col-xl-12 col-sm-12 mb-12">
			@if(session()->has('message'))
			    <div class="alert alert-success">
			        {{ session()->get('message') }}
			    </div>
			@endif

			<div class="card o-hidden h-100">
				<div class="card-header d-flex justify-content-between align-items-center">
					<h4>
						Painting Listing
					</h4>
					<form action="{{ route('paintings.listing') }}" method="GET" role="search" class="d-flex">
						<input type="text" class="form-control" placeholder="Search" name="name" value="{{ Request::input('name') }}" required>
						<div class="input-group">
							&nbsp;
							<input type="submit" value="Search" class="btn btn-info">
							&nbsp;
							<a href="{{ route('paintings.listing') }}" class="btn btn-success">Reset</a>
						</div>
					</form>
				</div>
				<div class="card-body">
					<div class="table-responsive">          
						<table class="table table-bordered">
							<thead>
								<tr>
									<th>Id</th>
									<th>Name</th>
									<th>Image</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								@if(count($paintings) > 0)
									@foreach($paintings as $painting)
										<tr>
											<td>{{$painting->id}}</td>
											<td>{{$painting->name}}</td>
											<td>
												<img src="{{ asset('images/'.$painting->image)}}" alt="..." style="height: 50px; width: 50px;">
											</td>
											<td>
												<a href="{{ route('paintings.detail', ['id' => $painting->id]) }}" class="btn btn-info ml-1" style="height: 35px; width: 100px;">
													<i class="far fa-eye"></i>VIEW
												</a>
											</td>
										</tr>
									@endforeach
								@else
									<tr>
										<td colspan="4">{{ 'No Record Found ! Try Again!!' }}</td>
									</tr>
								@endif
							</tbody>
						</table>
						{{ $paintings->links() }}
					</div>	
				</div>
			</div>
		</div>
	</div>
@endsection