routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*Route::group(["middleware" => "auth", "namespace" => "Admin"], function(){
	Route::get('/dashboard', 'DashboardController@adminDashboard')->name('admindashboard');
	Route::get('/userdashboard', 'DashboardController@userDashboard')->name('userdashboard');
});*/

Route::namespace('Admin\Login')->group(function(){
	Route::get('/login', 'LoginController@showForm')->name('login');
	Route::post('/login', 'LoginController@login');
	Route::post('/logout', 'LoginController@logout')->name('logout');
});

Route::group(["middleware" => ["auth","preventBackHistory"], "namespace" => "Admin"], function(){
	Route::get('/dashboard', 'DashboardController@adminDashboard')->name('admindashboard');
	Route::get('/userdashboard', 'DashboardController@userDashboard')->name('userdashboard');
});

Route::namespace('Admin\Auth')->group(function(){
	Route::get('/login', 'LoginController@showForm')->name('login');
	Route::post('/login', 'LoginController@login');
	Route::post('/logout', 'LoginController@logout')->name('logout');
	Route::get('/passwordReset', 'ForgetPasswordController@showForm')->name('password.request');
	Route::post('/password/email', 'ForgetPasswordController@sendEmail')->name('password.email');
	Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
	Route::post('password/reset', 'ResetPasswordController@resetPassword')->name('password.update');
});

Route::namespace('Admin\User')->group(function(){
	Route::prefix('users')->name('users.')->group(function(){
		Route::get('/', 'UsersController@index')->name('index');
		Route::get('/register', 'UsersController@create')->name('create');
		Route::post('/', 'UsersController@store')->name('store');
		Route::get('/edit/{id}', 'UsersController@edit')->name('edit');
		Route::put('/{id}', 'UsersController@update')->name('update');
		Route::delete('/delete/{id}', 'UsersController@destroy')->name('delete');
		Route::post('/{id}', 'UsersController@status')->name('status');
	});
});

Route::namespace('Admin\Exhibition')->group(function(){
	Route::prefix('exhibitions')->name('exhibitions.')->group(function(){
		Route::get('/', 'ExhibitionController@index')->name('index');
		Route::get('/create', 'ExhibitionController@create')->name('create');
		Route::post('/', 'ExhibitionController@store')->name('store');
		Route::get('view/{id}', 'ExhibitionController@show')->name('show');
		Route::get('/edit/{id}', 'ExhibitionController@edit')->name('edit');
		Route::put('/{id}', 'ExhibitionController@update')->name('update');
		Route::delete('/delete/{id}', 'ExhibitionController@destroy')->name('delete');
		Route::post('/{id}', 'ExhibitionController@status')->name('status');
	});
});

Route::namespace('Admin\Painting')->group(function(){
	Route::prefix('paintings')->name('paintings.')->group(function(){
		Route::get('/', 'PaintingController@index')->name('index');
		Route::get('/create', 'PaintingController@create')->name('create');
		Route::post('/', 'PaintingController@store')->name('store');
		Route::get('/edit/{id}', 'PaintingController@edit')->name('edit');
		Route::put('/{id}', 'PaintingController@update')->name('update');
		Route::delete('/delete/{id}', 'PaintingController@destroy')->name('delete');
		Route::post('/{id}', 'PaintingController@status')->name('status');
		Route::get('listing', 'PaintingController@listing')->name('listing');
		Route::get('detail/{id}', 'PaintingController@show')->name('detail');
	});
});

Route::namespace('Admin')->group(function (){
	Route::get('export', 'ExportController@export')->name('export');
});

/*Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');*/

app/Exhibition.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Painting;

class Exhibition extends Model
{
	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
	    'name', 'start_datetime', 'end_datetime', 'address', 'city', 'state', 'status',
	];

	/**
	 * Scope a query to search users.
	 *
	 * @param  \Illuminate\Database\Eloquent\Builder  $query
	 * @return \Illuminate\Database\Eloquent\Builder
	*/
	public function scopeFilter($query, $value)
	{
	    $query->where('name', 'LIKE', "%$value%");
	}
	
    /**
     * Get the Paintings.
     */
    public function paintings()
    {
        return $this->hasMany('App\Painting');
    }
}

app/Http/Controllers/API/ExhibitionController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Repositories\ExhibitionRepository;
use League\Fractal\Resource\Collection;
use League\Fractal\Resource\Item;
use League\Fractal\Manager;
use League\Fractal\Serializer\JsonApiSerializer;
use League\Fractal\Pagination\IlluminatePaginatorAdapter;
use App\Transformers\ExhibitionTransformer;
use Validator;


class ExhibitionController extends Controller
{
    protected $exhibition;

    public function __construct(ExhibitionRepository $exhibition)
    {
        $this->exhibition = $exhibition;
    }

    /**
     * @param \IIluminate\Http\Request $request
     * @return \IIluminate\Http\Response
     */
    public function index(Request $request)
    {
    	$paginator = $this->exhibition->paginate($request);
    	$exhibitions = $paginator->getCollection();
    	$manager = new Manager();
        $manager->setSerializer(new JsonApiSerializer(url('api')));
        $resource = new Collection($exhibitions, new ExhibitionTransformer(), 'exhibition');
    	$result = $resource->setPaginator(new IlluminatePaginatorAdapter($paginator));
    	return response()->json($manager->createData($result)->toArray());
    }

    /**
     * Store Request at Storage
     * @param \IILuminate\Http\Request $request
     */
    public function store(Request $request)
    {
		$validator = Validator::make($request->all(), [ 
	        'name' => 'required',
            'start_at' => 'required|date|date_format:Y-m-d|before:end_at',
            'end_at' => 'required|date|date_format:Y-m-d|after:start_at',
            'address' => 'required',
            'city' => 'required',
            'state' => 'required',
            'status' => 'accepted',
	    ]);
	    if ($validator->fails()) { 
	        return response()->json(['error'=>$validator->errors()], 401);            
	    }
	    $this->exhibition->store($request);
	    $exhibition = $this->exhibition->latestRecord();
        $manager = new Manager();
        $manager->setSerializer(new JsonApiSerializer(url('api')));
        $resource = new Item($exhibition, new ExhibitionTransformer(), 'Exhibition');
        $manager->parseIncludes('paintings');
        $result = $manager->createData($resource);
        return $result->toArray();
    }

    /**
     * Show Specific Exhibition
     * @param [int] $id
     * @return \IIluminate\Http\Response
     */
    public function show($id)
    {
    	$exhibition = $this->exhibition->view($id);
    	$manager = new Manager();
    	$manager->setSerializer(new JsonApiSerializer(url('api')));
    	$resource = new Item($exhibition, new ExhibitionTransformer(), 'Exhibition');
    	$manager->parseIncludes('paintings');
    	$result = $manager->createData($resource);
    	return $result->toArray();
    }

    /**
     * Update Specific Exhibition
     * @param [int] $id
     * @param \IIluminate\Http\Request $request
     * @return \IIluminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    	$this->exhibition->update($id, $request);
    	$exhibition = $this->exhibition->view($id);
        $manager = new Manager();
        $manager->setSerializer(new JsonApiSerializer(url('api')));
        $resource = new Item($exhibition, new ExhibitionTransformer(), 'Exhibition');
        $manager->parseIncludes('paintings');
        $result = $manager->createData($resource);
        return $result->toArray();
    }

    /**
     * Delete Specific Exhibition
     * @param [int] $id
     * @return \IIluminate\Http\Response
     */
    public function destroy($id)
    {
    	$this->exhibition->delete($id);
    	return response()->json(['message' => 'Exhibition Deleted Successfully'],200);
    }
}

app/Http/Controllers/Admin/Exhibition/ExhibitionController.php
<?php

namespace App\Http\Controllers\Admin\Exhibition;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\ExhibitionStoreRequest;
use App\Repositories\ExhibitionRepository;

class ExhibitionController extends Controller
{
    protected $exhibition;

    public function __construct(ExhibitionRepository $exhibition)
    {
        $this->exhibition = $exhibition;
    }
    /**
     * Display a listing of the Exhibitions.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $exhibitions = $this->exhibition->paginate($request);
        return view('admin.exhibitions.exhibition', [
            'exhibitions' => $exhibitions 
        ]);
    }

    /**
     * Show the form for creating a new Exhibition.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.exhibitions.create');
    }

    /**
     * Store a newly created Exhibition in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ExhibitionStoreRequest $request)
    {
        $this->exhibition->store($request);
        return redirect()->route('exhibitions.index')->with('message', 'Exhibition Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {   
        $exhibition = $this->exhibition->view($id);
        return view('admin.exhibitions.exhibitionView', [
            'exhibition' => $exhibition
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $exhibition = $this->exhibition->find($id);
        return view('admin.exhibitions.edit', [
            'exhibition' => $exhibition
        ]);  
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ExhibitionStoreRequest $request, $id)
    {
        $this->exhibition->update($id, $request);
        return redirect()->route('exhibitions.index')->with('message', 'Exhibition Created Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->exhibition->delete($id);
        return redirect()->route('exhibitions.index')->with('message', 'Exhibition Deleted Successfully');
    }

    /**
     * Update the specified Exhibition Status in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function status(Request $request, $id)
    {
        $this->exhibition->statusUpdate($id, $request);
        return redirect()->route('exhibitions.index')->with('message', 'Exhibition Status Updated Successfully');
    }
}

resources/views/admin/exhibitions/create.blade.php
@extends('admin.layout.master')
@section('title', 'Dashboard')
@section('content')
	<!-- Breadcrumbs-->
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="#">Admin Dashboard</a>
		</li>
		<li class="breadcrumb-item active">Overview</li>
	</ol>

	<!-- Users Listing-->
	<div class="row">
		<div class="col-xl-12 col-sm-12 mb-12">
			<div class="card o-hidden h-100">
				<div class="card-header d-flex justify-content-between align-items-center">
					<h4>
						Exhibition
					</h4>
				</div>
				<div class="card-body">
					<form action="{{ route('exhibitions.store') }}" method="POST">
						@csrf
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>Name:<large class="text-danger">*</large></label>
									<input type="text" name="name" class="form-control" value="{{ old('name') }}">
									@error('name')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>Start Date:<large class="text-danger">*</large></label>
									<input type="date" name="start_at" class="form-control" value="{{ old('start_at') }}">
									@error('start_at')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>End Date:<large class="text-danger">*</large></label>
									<input type="date" name="end_at" class="form-control" value="{{ old('end_at') }}">
									@error('end_at')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>Address:<large class="text-danger">*</large></label>
									<textarea id="content" name="address" cols="30" rows="5" class="form-control">
										{{{ old('address') }}}
									</textarea>
									@error('address')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>City:<large class="text-danger">*</large></label>
									<input type="text" name="city" class="form-control" value="{{ old('city') }}">
									@error('city')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>State:<large class="text-danger">*</large></label>
									<input type="text" name="state" class="form-control" value="{{ old('state') }}">
									@error('state')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>Status:</label>
									<input type="hidden" name="status" value="0">
									<input type="checkbox" name="status" value="1" class="mt-1" @if(old('status')=='1')) checked @endif>
									@error('status')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<input type="submit" name="exhibition" value="Add" class="btn btn-primary">
									<a href="{{ route('exhibitions.index') }}" class="btn btn-success">
										Back
									</a>
								</div>
							</div>
						</div>
					</form>	
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/admin/exhibitions/edit.blade.php
@extends('admin.layout.master')
@section('title', 'Dashboard')
@section('content')
	<!-- Breadcrumbs-->
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="#">Admin Dashboard</a>
		</li>
		<li class="breadcrumb-item active">Overview</li>
	</ol>

	<!-- Users Listing-->
	<div class="row">
		<div class="col-xl-12 col-sm-12 mb-12">
			<div class="card o-hidden h-100">
				<div class="card-header d-flex justify-content-between align-items-center">
					<h4>
						Edit Exhibition
					</h4>
				</div>
				<div class="card-body">
					<form action="{{ route('exhibitions.update', ['id' => $exhibition->id]) }}" method="POST">
						@method('PUT')
						@csrf
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>Name:</label>
									<input type="text" name="name" class="form-control" value="{{ $exhibition->name }}">
									@error('name')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>Start Date:</label>
									<input class="form-control" type="date" name="start_at" placeholder="Start Date" value="{{Carbon\Carbon::parse($exhibition->start_datetime)->format('Y-m-d')}}">
									@error('start_at')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>End Date:</label>
									<input class="form-control" type="date" name="end_at" placeholder="End Date" value="{{Carbon\Carbon::parse($exhibition->end_datetime)->format('Y-m-d')}}">
									@error('end_at')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>Address:</label>
									<textarea id="content" name="address" cols="30" rows="5" class="form-control">
										{{{ $exhibition->address }}}
									</textarea>
									@error('address')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>City:</label>
									<input type="text" name="city" class="form-control" value="{{ $exhibition->city }}">
									@error('city')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>State:</label>
									<input type="text" name="state" class="form-control" value="{{ $exhibition->state }}">
									@error('state')
									    <div class="text-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<label>Status:</label>
									<input type="hidden" name="status" value="0">
									<input type="checkbox" name="status" value="1" @if($exhibition->status == 1){{'checked'}}@endif>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xl-8">
								<div class="form-group">
									<input type="submit" name="exhibition" value="Update" class="btn btn-primary">
									<a href="{{ route('exhibitions.index') }}" class="btn btn-success">
										Back
									</a>
								</div>
							</div>
						</div>
					</form>	
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/admin/exhibitions/exhibition.blade.php
@extends('admin.layout.master')
@section('title', 'Dashboard')
@section('content')
	<!-- Breadcrumbs-->
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="#">Admin Dashboard</a>
		</li>
		<li class="breadcrumb-item active">Overview</li>
	</ol>

	<!-- Exhibitions Listing-->
	<div class="row">
		<div class="col-xl-12 col-sm-12 mb-12">
			@if(session()->has('message'))
			    <div class="alert alert-success">
			        {{ session()->get('message') }}
			    </div>
			@endif
			<div class="card o-hidden h-100">
				<div class="card-header d-flex justify-content-between align-items-center">
					<h4>
						Exhibition Listing
					</h4>
					<form action="{{ route('exhibitions.index') }}" method="GET" role="search" class="d-flex">
						<input type="text" class="form-control" placeholder="Search" name="name" value="{{ Request::input('name') }}" required>
						<div class="input-group">
							&nbsp;
							<input type="submit" value="Search" class="btn btn-info">
							&nbsp;
							<a href="{{ route('exhibitions.index') }}" class="btn btn-success">Reset</a>
						</div>
					</form>
					<a href="{{ route('exhibitions.create') }}" class="btn btn-success">
						Add Exhibition
					</a>
				</div>
				<div class="card-body">
					<div class="table-responsive">          
						<table class="table table-bordered">
							<thead>
								<tr>
									<th>Id</th>
									<th>Name</th>
									<th>Start Date/Time</th>
									<th>End Date/Time</th>
									<th>Address</th>
									<th>City</th>
									<th>State</th>
									<th>Status</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								@if(count($exhibitions) > 0)
									@foreach($exhibitions as $exhibition)
										<tr>
											<td>{{$exhibition->id}}</td>
											<td>{{$exhibition->name}}</td>
											<td>{{date('d/m/Y', strtotime($exhibition->start_datetime))}}</td>
											<td>{{date('d/m/Y', strtotime($exhibition->end_datetime))}}</td>
											<td>{!!$exhibition->address!!}</td>
											<td>{{$exhibition->city}}</td>
											<td>{{$exhibition->state}}</td>
											<td>
												<form action="{{ route('exhibitions.status', ['id' => $exhibition->id]) }}" method="POST">
													{{ csrf_field() }}
													@if($exhibition->status == 1)
														<input type="hidden" name="status" value="0">
														<button type="submit" class="btn btn-success">
															<i class="fas fa-user-check" style="font-size: 10px;"></i>
														</button>
													@else
														<input type="hidden" name="status" value="1">
														<button type="submit" class="btn btn-danger">
															<i class="fas fa-window-close" style="font-size: 10px;"></i>
														</button>
													@endif
												</form>
											</td>
											<td class="d-flex">
												<a href="{{ route('exhibitions.show', ['id' => $exhibition->id]) }}" class="btn btn-info mr-1" style="height: 30px; width: 42px;">
													<i class="far fa-eye"></i>
												</a>
												<form method="POST" action="{{ route('exhibitions.delete', ['id' => $exhibition->id]) }}">
												    {{ csrf_field() }}
												    {{ method_field('DELETE') }}
												    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">
												    	<i class="fas fa-trash-alt"></i>
												    </button>
												</form>
												<a href="{{ route('exhibitions.edit', ['id' => $exhibition->id]) }}" class="btn btn-info ml-1" style="height: 30px; width: 42px;">
													<i class="far fa-edit"></i>
												</a>
											</td>
										</tr>
									@endforeach
								@else
									<tr>
										<th colspan="9">No Record's Found ! Try Again !!</th>
									</tr>
								@endif	
							</tbody>
						</table>
						{{ $exhibitions->links() }}
					</div>	
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/admin/exhibitions/exhibitionView.blade.php
@extends('admin.layout.master')
@section('title', 'Dashboard')
@section('content')
	<!-- Breadcrumbs-->
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="#">Admin Dashboard</a>
		</li>
		<li class="breadcrumb-item active">Overview</li>
	</ol>

	<!-- Exhibitions Listing-->
	<div class="row">
		<div class="col-xl-12 col-sm-12 mb-12">
			@if(session()->has('message'))
			    <div class="alert alert-success">
			        {{ session()->get('message') }}
			    </div>
			@endif
			<div class="card o-hidden h-100">
				<div class="card-header d-flex justify-content-between align-items-center">
					<h4>
						Exhibition Detail
					</h4>
					<a href="{{ route('exhibitions.index') }}" class="btn btn-success">
						Back
					</a>
				</div>
				<div class="card-body">
					<div class="table-responsive">
						<table class="table table-bordered">
							<tr>
								<th>Exhibition Name:</th>
								<td>{{$exhibition->name}}</td>
							</tr>
							<tr>
								<th>Start Date:</th>
								<td>{{date('d/m/Y', strtotime($exhibition->start_datetime))}}</td>
							</tr>
							<tr>
								<th>End Date:</th>
								<td>{{date('d/m/Y', strtotime($exhibition->end_datetime))}}</td>
							</tr>
							<tr>
								<th>Status:</th>
								<td>
									@if($exhibition->status == 1)
									<button type="button" class="btn btn-success">
										<i class="fas fa-user-check"></i>{{'Active'}}
									</button>
									@else
										<button type="button" class="btn btn-success">
											<i class="fas fa-close"></i>{{'Deactive'}}
										</button>
									@endif
								</td>
							</tr>
							<tr>
								<th>Venue:</th>
								<td>{!!$exhibition->address!!},&nbsp;{{$exhibition->city}},&nbsp;{{$exhibition->state}}</td>
							</tr>
							<tr>
								<th>Paintings:</th>
								<td>
									@foreach($exhibition->paintings as $painting)
										<table class="border" width="100%">
											<tr>
												<th>Painting Name:</th>
												<td>{{$painting->name}}</td>
											</tr>
											<tr>
												<th>Images:</th>
												<td>
													<img src="{{ asset('images/'.$painting->image) }}" alt="..." height="70px" width="100px">
												</td>
											</tr>
										</table>
									@endforeach
								</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection