routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*Route::group(["middleware" => "auth", "namespace" => "Admin"], function(){
	Route::get('/dashboard', 'DashboardController@adminDashboard')->name('admindashboard');
	Route::get('/userdashboard', 'DashboardController@userDashboard')->name('userdashboard');
});*/

Route::namespace('Admin\Login')->group(function(){
	Route::get('/login', 'LoginController@showForm')->name('login');
	Route::post('/login', 'LoginController@login');
	Route::post('/logout', 'LoginController@logout')->name('logout');
});

Route::group(["middleware" => ["auth","preventBackHistory"], "namespace" => "Admin"], function(){
	Route::get('/dashboard', 'DashboardController@adminDashboard')->name('admindashboard');
	Route::get('/userdashboard', 'DashboardController@userDashboard')->name('userdashboard');
});

Route::namespace('Admin\Auth')->group(function(){
	Route::get('/login', 'LoginController@showForm')->name('login');
	Route::post('/login', 'LoginController@login');
	Route::post('/logout', 'LoginController@logout')->name('logout');
	Route::get('/passwordReset', 'ForgetPasswordController@showForm')->name('password.request');
	Route::post('/password/email', 'ForgetPasswordController@sendEmail')->name('password.email');
	Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
	Route::post('password/reset', 'ResetPasswordController@resetPassword')->name('password.update');
});

Route::namespace('Admin\User')->group(function(){
	Route::prefix('users')->name('users.')->group(function(){
		Route::get('/', 'UsersController@index')->name('index');
		Route::get('/register', 'UsersController@create')->name('create');
		Route::post('/', 'UsersController@store')->name('store');
		Route::get('/edit/{id}', 'UsersController@edit')->name('edit');
		Route::put('/{id}', 'UsersController@update')->name('update');
		Route::delete('/delete/{id}', 'UsersController@destroy')->name('delete');
		Route::post('/{id}', 'UsersController@status')->name('status');
	});
});

Route::namespace('Admin\Exhibition')->group(function(){
	Route::prefix('exhibitions')->name('exhibitions.')->group(function(){
		Route::get('/', 'ExhibitionController@index')->name('index');
		Route::get('/create', 'ExhibitionController@create')->name('create');
		Route::post('/', 'ExhibitionController@store')->name('store');
		Route::get('view/{id}', 'ExhibitionController@show')->name('show');
		Route::get('/edit/{id}', 'ExhibitionController@edit')->name('edit');
		Route::put('/{id}', 'ExhibitionController@update')->name('update');
		Route::delete('/delete/{id}', 'ExhibitionController@destroy')->name('delete');
		Route::post('/{id}', 'ExhibitionController@status')->name('status');
	});
});

Route::namespace('Admin\Painting')->group(function(){
	Route::prefix('paintings')->name('paintings.')->group(function(){
		Route::get('/', 'PaintingController@index')->name('index');
		Route::get('/create', 'PaintingController@create')->name('create');
		Route::post('/', 'PaintingController@store')->name('store');
		Route::get('/edit/{id}', 'PaintingController@edit')->name('edit');
		Route::put('/{id}', 'PaintingController@update')->name('update');
		Route::delete('/delete/{id}', 'PaintingController@destroy')->name('delete');
		Route::post('/{id}', 'PaintingController@status')->name('status');
		Route::get('listing', 'PaintingController@listing')->name('listing');
		Route::get('detail/{id}', 'PaintingController@show')->name('detail');
	});
});

Route::namespace('Admin')->group(function (){
	Route::get('export', 'ExportController@export')->name('export');
});

/*Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');*/

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'status',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Scope a query to search users.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
    */
    public function scopeFilter($query, $value)
    {
        $query->where('name', 'LIKE', "%$value%");
    }
    
    public function paintings()
    {
        return $this->hasMany('App\Painting');
    }
}

app/Http/Controllers/API/UsersController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Repositories\UserRepository;
use App\Transformers\UserTransformer;
use League\Fractal\Resource\Collection;
use League\Fractal\Resource\Item;
use League\Fractal\Manager;
use League\Fractal\Serializer\JsonApiSerializer;
use League\Fractal\Pagination\IlluminatePaginatorAdapter;
use Validator;

class UsersController extends Controller
{
	protected $user;

	public function __construct(UserRepository $user)
	{
	    $this->user = $user;
	}

	/**
	 * @return \IIluminate\Http\Response
	 */
	public function index(Request $request)
	{
        $paginator = $this->user->paginate($request);
        $users = $paginator->getCollection();
        $manager = new Manager();
        $manager->setSerializer(new JsonApiSerializer(url('api')));
        $resource = new Collection($users, new UserTransformer(), 'user');
        $result = $resource->setPaginator(new IlluminatePaginatorAdapter($paginator));
        return response()->json($manager->createData($result)->toArray());
	}

    /**
     * @param [int] $id
     * @return \IIluminate\Http\Response
     */
    public function show($id)
    {
    	$user = $this->user->show($id);
    	$manager = new Manager();
    	$manager->setSerializer(new JsonApiSerializer(url('api')));
    	$resource = new Item($user, new UserTransformer(), 'user');
    	$result = $manager->createData($resource);
    	return $result->toArray();
    }

    /**
     * @param [int] $id
     * @param \IIluminate\Http\Request $request
     * @return \IIluminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    	$this->user->update($id, $request);
    	$user = $this->user->show($id);
        $manager = new Manager();
        $manager->setSerializer(new JsonApiSerializer(url('api')));
        $resource = new Item($user, new UserTransformer(), 'user');
        $result = $manager->createData($resource)->toArray();
        return $result;
    }

    /**
     * @param [int] $id
     * @return \IIluminate\Http\Response
     */
    public function destroy($id)
    {
    	$this->user->delete($id);
    	return response()->json(['message' => 'User Deleted Successfully'],200);
    }
}

app/Http/Controllers/Admin/User/UsersController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\UserStoreRequest;
use App\Repositories\UserRepository;

class UsersController extends Controller
{
    protected $user;

    public function __construct(UserRepository $user)
    {
        $this->user = $user;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = $this->user->paginate($request);
        return view('admin.users.users', [
            'users' => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.auth.register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserStoreRequest $request)
    {
        $this->user->store($request);
        return redirect()->route('users.create')->with('message', 'User Registered Successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->user->find($id);
        return View('admin.users.edit', [
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserStoreRequest $request, $id)
    {
        $this->user->update($id, $request);
        return redirect()->route('users.index')->with('message', 'User Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->user->delete($id);
        return redirect()->route('users.index')->with('message', 'User Deleted Successfully');
    }

    /**
     * Update the specified User Status in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function status(Request $request, $id)
    {
        $this->user->statusUpdate($id, $request);
        return redirect()->route('users.index')->with('message', 'User Status Updated Successfully');
    }
}

resources/views/admin/users/edit.blade.php
@extends('admin.layout.master')
@section('title', 'Dashboard')
@section('content')
	<!-- Breadcrumbs-->
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="#">Admin Dashboard</a>
		</li>
		<li class="breadcrumb-item active">Overview</li>
	</ol>

	<!-- Users Listing-->
	<div class="row">
		<div class="col-xl-12 col-sm-12 mb-12">
			<div class="card o-hidden h-100">
				<div class="card-header">
					<h4>
						Edit User
					</h4>
				</div>
				<div class="card-body">
					<div class="form">
						<form action="{{ route('users.update', ['id' => $user->id]) }}" method="POST">
							@method('PUT')
						    @csrf
						    <div class="row">
						        <div class="col-xl-6">
						            <div class="form-group">
						                <label for="">Name:</label>
						                <input type="text" name="name" class="form-control" value="{{ $user->name }}">
						                @error('name')
						                    <div class="text-danger">{{ $message }}</div>
						                @enderror
						            </div>
						        </div>
						    </div>
						    <div class="row">
						        <div class="col-xl-6">
						            <div class="form-group">
						                <label for="">Email:</label>
						                <input type="text" name="email" class="form-control" value="{{ $user->email }}">
						                @error('email')
						                    <div class="text-danger">{{ $message }}</div>
						                @enderror
						            </div>
						        </div>
						    </div>
						    <div class="row">
								<div class="col-xl-6">
									<div class="form-group">
										<label>Status:</label>
										<input type="hidden" name="status" value="0">
										<input type="checkbox" name="status" value="1" @if($user->status == 1){{'checked'}}@endif>
									</div>
								</div>
						    </div>
						    <div class="row">
						        <div class="col-xl-6">
						            <div class="form-group">
						                <input type="submit" name="submit" class="btn btn-primary" value="Update">
						                <a class="btn btn-success" href="{{ route('users.index') }}">Back</a>
						            </div>
						        </div>
						    </div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/admin/users/users.blade.php
@extends('admin.layout.master')
@section('title', 'Dashboard')
@section('content')
	<!-- Breadcrumbs-->
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="#">Admin Dashboard</a>
		</li>
		<li class="breadcrumb-item active">Overview</li>
	</ol>

	<!-- Users Listing-->
	<div class="row">
		<div class="col-xl-12 col-sm-12 mb-12">
			@if(session()->has('message'))
			    <div class="alert alert-success">
			        {{ session()->get('message') }}
			    </div>
			@endif
			<div class="card o-hidden h-100">
				<div class="card-header d-flex align-items-center justify-content-between">
					<h4>
						User Listing
					</h4>
					<form action="{{ route('users.index') }}" method="GET" role="search" class="d-flex">
						<input type="text" class="form-control" placeholder="search" name="name" value="{{ Request::input('name') }}" required>
						<div class="input-group">
							&nbsp;
							<input type="submit" value="Search" class="btn btn-info">
							&nbsp;
							<a href="{{ route('users.index') }}" class="btn btn-success">Reset</a>
						</div>
					</form>
					<a class="btn btn-warning" href="{{ route('export', ['name'=> app('request')->input('name')]) }}">Export User Data</a>
				</div>
				<div class="card-body">
					<div class="table-responsive">          
						<table class="table table-bordered">
							<thead>
								<tr>
									<th>Id</th>
									<th>Name</th>
									<th>Email</th>
									<th>Status</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								@if(count($users) > 0)
									@foreach($users as $user)
										<tr>
											<td>{{ $user->id }}</td>
											<td>{{ $user->name }}</td>
											<td>{{ $user->email}}</td>
											<td>
												<form action="{{ route('users.status', ['id' => $user->id]) }}" method="POST">
													{{ csrf_field() }}
													@if($user->status == 1)
														<input type="hidden" name="status" value="0">
														<button type="submit" class="btn btn-success">
															<i class="fas fa-user-check" style="font-size: 10px"></i>
														</button>
													@else
														<input type="hidden" name="status" value="1">
														<button type="submit" class="btn btn-danger">
															<i class="fas fa-window-close" style="font-size: 10px"></i>
														</button>
													@endif
												</form>
											</td>
											<td class="d-flex">
												<form method="POST" action="{{ route('users.delete', ['id' => $user->id]) }}">
												    {{ csrf_field() }}
												    {{ method_field('DELETE') }}
												    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">
												    	<i class="fas fa-trash-alt"></i>
												    </button>
												</form>
												<a href="{{ route('users.edit', ['id' => $user->id]) }}" class="btn btn-info ml-1" style="height: 30px; width: 42px;">
													<i class="far fa-edit"></i>
												</a>
											</td>	
										</tr>
									@endforeach
								@else
									<tr>
										<th colspan="5">No Record's Found</th>
									</tr>
								@endif
							</tbody>
						</table>
						{{ $users->links() }}
					</div>	
				</div>
			</div>
		</div>
	</div>
@endsection